### ISSUE TITLE
Subthemes are missing in ConcernedThemes

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#14]
Für das Grundstück Wisen GB-Nr. 135:
- https://geo.so.ch/map/?k=e97f81c1e
- http://localhost:8080/extract/reduced/xml/geometry/CH540632893416

werden im Auszug zwei betroffene Theme ausgewiesen:
- Nutzungsplanung
- Lärmempfindlichkeitsstufen

Bei den NotConcernedTheme werden dann die Subthemen der Nutzungsplanung aufgelistet, so z.B. auch die Grundnutzung.

Schein noch was krumm zu sein. Oder hat das was mit den Daten im Annex-Modell zu tun?

![Screenshot 2019-08-17 at 18 39 39](https://user-images.githubusercontent.com/2767800/63214904-dba95c80-c11e-11e9-94ee-c0bab5ebc3a3.png)

**Comment by claeis** [comment]
siehe auch a1f89c8149400dc9495f32981411529ce2610f41

Aber macht es wirklich Sinn, hier in der Uebersicht alle Sub-Themen aufzuführen.
