### ISSUE TITLE
Wrong translated theme text

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#17]
Jetzt steht fast überall (dort wo es kein Subthema gibt?) beim deutschen Thementext nur noch "Thematitel". 

[CH533287066291.xml.zip](https://github.com/claeis/oereb-web-service/files/3596595/CH533287066291.xml.zip)

**Comment by claeis** [comment]
Sieht so aus, wie wenn  OeREBKRM_V1_1_Codelisten_20170101.xml in der DB fehlt...

**Comment by edigonzales** [comment]
Ja. Hat sich erledigt. Ich weiss nicht, ob es nur in der GDI oder auch lokal auftrat. Bei mir wäre es es nicht an den Codelisten gelegen, die habe ich immer interpretiert. Jedoch in der GDI fehlten sie.
