### ISSUE TITLE
PLRCadastreAuthority wrong name

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#19]
"OEREB-Katasteramt" ist falsch. Soweit ich mich noch erinnere, wird über die URL der Name etc. aus dem Annex gelesen (?)

![Screenshot 2019-09-12 at 16 55 37](https://user-images.githubusercontent.com/2767800/64795393-4f078800-d57e-11e9-90dd-2d26c607e41a.png)

**Comment by claeis** [comment]
ja, aber dazu muss die richtige URL konfiguriert sein. Richtig ist eine, zu der es einen Eintrag in den Annex-Daten gibt. Wenn es den Eintrag (hier offenbar ```https://agi.so.ch```) nicht gibt, kommt "OEREB-Katasteramt"

**Comment by edigonzales** [comment]
Momentan steht nur `<OfficeAtWeb>agi.so.ch</OfficeAtWeb>` drin.

**Comment by claeis** [comment]
aber nicht gem  https://github.com/sogis/oereb-web-service-docker/blob/56462bbcf1c377c22a73004bf33fc78f9cb30a80/Dockerfile#L22

**Comment by claeis** [comment]
Und in den Stammdaten vom 2019-08-12 steht ```<OfficeAtWeb>https://www.agi.so.ch</OfficeAtWeb>```

**Comment by claeis** [comment]
Was wäre richtig?

**Comment by edigonzales** [comment]
Ich spiele/teste es mit https://agi.so.ch durch und korrigiere und update die Daten.

**Comment by edigonzales** [comment]
Funktioniert.
