### ISSUE TITLE
Superfluous ThemeWithoutData

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#24]
```
    <ns6:ThemeWithoutData>
      <ns6:Code>LandUsePlans</ns6:Code>
      <ns6:Text>
        <ns6:Language>de</ns6:Language>
        <ns6:Text>Nutzungsplanung (kantonal/kommunal)</ns6:Text>
      </ns6:Text>
    </ns6:ThemeWithoutData>
```

Sollte nicht erscheinen.

**Comment by edigonzales** [comment]
[CH368132060914_sorting_again.xml.zip](https://github.com/claeis/oereb-web-service/files/3626240/CH368132060914_sorting_again.xml.zip)

**Comment by claeis** [comment]
Bei einer Abfrage ohne TOPIC Parameneter, gilt implizit ALL, und damit sind m.E. implizit alle Bundesthemen gemeint. Darum erscheinen alle Bundesthemen (mindestens unter ThemeWithoutData). Ein Benutzer muss doch sehen, dass die Bundesthemen in diesem Kataster keine Daten haben, sonst sieht es in jedem Kanton anders aus.

**Comment by edigonzales** [comment]
Ich finde es aber auch so unglücklich. In unserem Fall ist "Nutzungsplanung (kantonal/kommunal)" ein "abstraktes" Thema. Es kann also davon also gar keine Instanz geben . So könnte man auch die PDF-Weisung (Kap. 2.5) interpretieren. 

Wenn jemand liest es gibt keine "Nutzungsplanung (kommunal/kantonal)", meint dieser jemand doch, dass es keine Daten zur Nutzungsplanung im Auszug gibt. Dabei haben wir alle Daten zur Nutzungsplanung in Subthemen aufgedrönselt.

Wird eine lustige Abnahme :)

**Comment by edigonzales** [comment]
Btw: Wir können die Sache natürlich mit V+D vorher diskutieren. Landet dann wohl wieder bei dir (?).

**Comment by claeis** [comment]
Gehört auch ins Kapitel unreifes SubThema. So etwas wie ein abstraktes Bundesthema (im Sinne von vollständig durch kantonale Sub-Themen abgedeckt), gibt es ja bis jetzt nicht. Ich nehm das Bundesthema raus (wenn es ein Sub-Thema hat).

**Comment by edigonzales** [comment]
Ich habe das eigentlich schon immer so interpretiert. Wenn es Subthemen gibt, gibt es direkt zum Thema keine Daten. Andere Usecases schienen mir nicht logisch. In diesen Fällen sähe ich eher das eigenständige, kantonale Thema mit einem sehr losen Bezug oder keinem zu einem Bundesthema.
