### ISSUE TITLE
Ermittlung betroffene ÖREB (Frage)

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#25]
Werden die betroffenen ÖREB hier ermittelt? https://github.com/claeis/oereb-web-service/blob/7f6e70f35c6b353bf16cf8b170ff0b64ea7fab53/src/main/java/ch/ehi/oereb/webservice/OerebController.java#L778

Und falls die Intersection < Toleranz ist (plusminus https://github.com/claeis/oereb-web-service/blob/7f6e70f35c6b353bf16cf8b170ff0b64ea7fab53/src/main/java/ch/ehi/oereb/webservice/OerebController.java#L1085), wird die Eigentumsbeschränkung verworfen?

**Comment by claeis** [comment]
ja

- die Kandidaten werden gem. Argument bbox von addRestrictions() auf der DB ermittelt
- die effektiven Ueberlappungen werden dann vor der zitierten Zeile 1085 ermittelt
