### ISSUE TITLE
Use specific timezone for creation date

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#26]
Die Uhrzeit im XML ist zwei Stunden zurück. Das hängt wohl damit zusammen, das der Openshift-Cluster auf UTC gesetzt ist.

a) `Calendar cal = new GregorianCalendar(TimeZone.getTimeZone("Europe/Zurich"));` verwenden.

oder 

b) Im Dockerfile die Systemlocale o.ä. überschreiben (falls das geht)

Was meinst du?

**Comment by claeis** [comment]
Ist ein haariges Probelm, weil in den Strukturen für die Zeit z.T. die Zeitzone fehlt, d.h. sie kann verloren gehen, und dann wird bei der weiteren Verarbeitung irgendein (falscher) Default verwendet. Aber: Wo stört dich das?

**Comment by edigonzales** [comment]
Auf dem PDF unten links.

**Comment by claeis** [comment]
Scheint mir falsch, wenn der Service die TimeZone setzt. D.h. man muss es im Conteiner setzen, oder der Comtainer muss es aus seiner Umgebung übernehmen.

**Comment by claeis** [comment]
docker run -e TZ=Europe/Zurich ....
