### ISSUE TITLE
Scale image bbox

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#3]
Die Boundingbox des Kartenbildes soll ein wenig grösser sein als die Boundingbox des Grundstückes.

**Comment by claeis** [comment]
Ist bereits der Fall (auf allen vier Seiten 5mm). Mehr?

**Comment by edigonzales** [comment]
Sieht bei mir aber noch so aus. Oben und unten ist das Grundstück bündig mit dem Kartenrand.

![Screenshot 2019-08-10 at 06 14 59](https://user-images.githubusercontent.com/2767800/62817398-3991df00-bb36-11e9-873f-98d58ed6e314.png)
