### ISSUE TITLE
Wrong SymbolRef url

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#30]
http://geo-t.so.ch/symbol/129070 sollte https://geo-t.so.ch/api/oereb/v1/symbol/129070 sein.

Ich weiss aber nicht, ob die Anwendung die korrekte URL kennen kann. Sonst müsste man wohl noch konfigurieren können.

**Comment by claeis** [comment]
Der Proxy muss so konfiguriert werden, dass er den nach aussen sichtbaren Hostnamen und Kontextpfad via x-forwarded-... http-Headers an den Service weiterleiten. Und der Service muss so konfiguriert werden, dass er diese http-Headers auswertet.

**Comment by claeis** [comment]
server.use-forward-headers=true und server.tomcat.internal-proxies zu setzen genuegt offenbar in der aktuellen spring version nicht, man muss ForwardedHeaderFilter benutzen, um die x-forwarded-.. headers auszuwerten
