### ISSUE TITLE
"Abstraktes" Bundesthema in ThemeWithoutData

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#31]
Das abstrakte Thema "Nutzungsplanung (kantonal/kommunal)" erscheint bei ThemeWithoutData.

[data_extract_9010031569295059646.xml.zip](https://github.com/claeis/oereb-web-service/files/3659337/data_extract_9010031569295059646.xml.zip)

**Comment by claeis** [comment]
Hast Du ch.SO.NutzungsplanungUeberlagernd und ch.SO.NutzungsplanungSondernutzungsplaene und ch.SO.NutzungsplanungGrundnutzung und ch.SO.Baulinien als Sub-Thema zu Nutzungsplanung konfiguriert (Annex.ThemaTxt/Code=Nutzungsplanung und nicht WeiteresThema) ?

**Comment by Luescher** [comment]
Ja ist als Sub-Thema von Nutzungsplanung erfasst
![nutzungsplanung](https://user-images.githubusercontent.com/3929984/76869786-1a47f680-6869-11ea-89e0-3bd971afb30d.jpg)

**Comment by edigonzales** [comment]
Abnahmeprotokoll: M-15

**Comment by claeis** [comment]
Ist das "abstrakte" Thema für die Gemeinde auch freigeschaltet?

**Comment by claeis** [comment]
...oder bei einer anderen Gemeinde?

**Comment by claeis** [comment]
Ich habe die Logik so geändert, dass nur noch Hauptthemen in ThemeWithoutData aufgeführt werden und zwar diejenigen, die abgefragt werden abzüglich der Themen, die für die Gemeinde freigeschaltet sind. Themen die für die Gemeinde freigeschaltet sind, erscheinen unter ConcernedTheme oder NotConcernedTheme (aber nie unter ThemeWithoutData)
