### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#33]
`web-service_1  | 2019-10-02 20:54:48.801  INFO 6 --- [io-8181-exec-10] ch.ehi.oereb.webservice.OerebController  : g_id 472534 e_id 483688 d_id 478970 aussage Baulinie Strasse kantonal`

Werden diese Meldungen noch bewusst geloggt (Info-Level)?

**Comment by claeis** [comment]
Ja, habe gedacht, das hilft vorläufig rasch Fehler im Service/den Daten zu finden. Aber kann von mir aus reduziert werden.

**Comment by edigonzales** [comment]
Falls es nach längerem Betrieb stört, wieder öffnen.
