### ISSUE TITLE
NPE when getSymbol handling goes wrong

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#34]
Falls einer Restriction keine Symbol zugewiesen werden kann resp. aus den LegendEntries, dem TypeCode und der TypeCodeliste keine Symbol gefunden werden kann:

https://github.com/claeis/oereb-web-service/blob/master/src/main/java/ch/ehi/oereb/webservice/OerebController.java#L1323

gibt es eine Nullpointerexception. Response status code ist 406.

**Comment by claeis** [comment]
Ist aber ein Datenfehler...Symbol oder SymbolRef ist zwingend in der Response.
Response status sollte 500 sein.
