### ISSUE TITLE
Anteil in % wie wird das gerechnet?

### ISSUE THREAD

**Issue by Luescher** [claeis/oereb-web-service#35]
Bei CH180532067365  (https://geo-t.so.ch/api/oereb/extract/reduced/xml/geometry/CH180532067365)

Fläche Grundstück: 630m2
Fläche Anteil Sicherheitszonenplan: 127m2 (`<ns3:AreaShare>127</ns3:AreaShare>`)

Berechnung  127/(630/100)= 20.158....

im XML steht` <ns3:PartInPercent> 20.1 </ns3:PartInPercent>`
Soll es nicht 20.2 sein?

**Comment by claeis** [comment]
Es werden die ungerundeten Werte für die Prozent Berechnung verwendet. Es wird die gerechnete Grundstücksfläche verwendet.
