### ISSUE TITLE
serviceEndpointBase bei GetVersions() sinnvoll?

### ISSUE THREAD

**Issue by Luescher** [claeis/oereb-web-service#37]
```
<ns9:GetVersionsResponse>
<ns9:supportedVersion>
<ns9:version>extract-1.0</ns9:version>
</ns9:supportedVersion>  
</ns9:GetVersionsResponse
```
`<serviceEndpointBase> `fehlt momentan

**Comment by claeis** [comment]
Das ist dafür gedacht, dass man eine andere Version (als eine andere Interface Version, nicht eine andere Implementierungsversion) die auf einem anderen Endpunkt läuft, entdecken kann.  Da dies die Version 1.0, kann das Feld kann darum weggelassen werden/wäre redundant (man hat ja genau diesen Endpunkt aufgerufen).
