### ISSUE TITLE
Law statt Hint

### ISSUE THREAD

**Issue by Luescher** [claeis/oereb-web-service#38]
Bei den Sicherzeitszonenplan ist das Dokument "Wichtige Hinweise" (108-INFO-D) im XML als DocumentType = LAW gemäss Abklärungen mit dem Bund soll das ein Hint sein.

Bsp. https://geo-t.so.ch/api/oereb/extract/reduced/xml/geometry/CH793273730603

**Comment by Luescher** [comment]
Ab dem 20. März werden die Systemabnahmen vom Bund gemacht. Das könnte ein Probelm resp. Mangel geben. Kann das vorgängig noch gefixt werden?

**Comment by Luescher** [comment]
Mail Claude:
Alle OeREBKRMvs_V1_1.Vorschriften.Dokument Objekte die in einem OeREBKRMtrsfr_V1_1.Transferstruktur Behälter vorkommen sind "Hint"s und nicht "Law". ("LegalProvision" sind OeREBKRMvs_V1_1.Vorschriften.Rechtsvorschrift Objekte)

"Law" sind nur OeREBKRMvs_V1_1.Vorschriften.Dokument Objekte die in einem OeREBKRMvs_V1_1.Vorschriften.Dokument Behälter vorkommen.

**Comment by Luescher** [comment]
Ja so sehen wir das auch.

**Comment by edigonzales** [comment]
@Luescher schliessen?

**Comment by Luescher** [comment]
Passt nun so. Merci fürs fixen.
