### ISSUE TITLE
Superflous OtherLegend

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#40]
http://oereb.sogeo.services/ws/extract/reduced/xml/geometry/CH770672653201

Im Thema "Baulinien Nationalstrassen" erscheint das Symbol des eigentlichen betroffenen ÖREB auch nochmals bei der übrigen Legende. 

Z.B. bei Nutzungsplanung passiert das nicht.

**Comment by edigonzales** [comment]
[CH770672653201.pdf.zip](https://github.com/claeis/oereb-web-service/files/4070182/CH770672653201.pdf.zip)

**Comment by claeis** [comment]
siehe auch #9 und #18

**Comment by edigonzales** [comment]
[CH770672653201_fixed.pdf.zip](https://github.com/claeis/oereb-web-service/files/4353876/CH770672653201_fixed.pdf.zip)

fixed: https://github.com/claeis/oereb-web-service/commit/916026be0b0ed796ef1844e4c0dda693f1f5c3cc
