### ISSUE TITLE
Missing OtherLegend

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#44]
OtherLegend fehlt jetzt leider komplett. Hat wohl mit https://github.com/claeis/oereb-web-service/issues/40 zu tun. Leider habe damals nur getestet, ob die überflüssigen weg sind. Und nicht ob die notwendigen noch vorhanden sind.

Z.B. 
https://geo.so.ch/api/oereb/extract/reduced/xml/geometry/CH955832730623
https://geo.so.ch/api/oereb/extract/reduced/pdf/CH955832730623

Thema: "Nutzungsplanung Grundnutzung" und "Baulinien"

Abnahmeprotokoll: M-13

**Comment by Luescher** [comment]
Merci für das fixen...

Beim Testen haben wir gesehen, dass zum Teil nochmals Legendeneinträge in "OtherLegend" kommen, die bereits schon ÖREB sind, die das Grundstück betreffen.

- Beispiel "Baulinie Strasse" die werden nochmals unter OtherLegend aufgeführt, obwohl sie auch unter RestrictionOnLandownership sind.
https://geo-t.so.ch/api/oereb/extract/reduced/xml/geometry/CH993287900649

- Beispiel "Wohnzone W2a" und "Kernzone" werden nochmals aufegführt
https://geo-t.so.ch/api/oereb/extract/reduced/xml/geometry/CH810658327355

Meine Vermutung... Wenn es in einem Ausschnitt mehr als ein Objekt mit demselben Code / Text hat, wird dies nochmals aufgeführt in OtherLegend.


![otherLegend](https://user-images.githubusercontent.com/3929984/80707276-ffb0a080-8ae9-11ea-9203-2fe7a4172b48.jpg)

**Comment by claeis** [comment]
Das XML bei CH993287900649 ist m.E. korrekt (also ist das Problem in pdf4oereb):

			<ns6:RestrictionOnLandownership>
				<ns6:Information>
					<ns6:LocalisedText>
						<ns6:Language>de</ns6:Language>
						<ns6:Text>Baulinie Strasse kantonal</ns6:Text>
					</ns6:LocalisedText>
				</ns6:Information>
				<ns6:TypeCode>7110</ns6:TypeCode>
				<ns6:TypeCodelist>urn:fdc:ilismeta.interlis.ch:2017:NP_Typ_Kanton_Erschliessung_Linienobjekt.2407</ns6:TypeCodelist>
				<ns6:OtherLegend>
						<ns6:LegendText>
							<ns6:LocalisedText>
								<ns6:Language>de</ns6:Language>
								<ns6:Text>Gestaltungsbaulinie kantonal</ns6:Text>
							</ns6:LocalisedText>
						</ns6:LegendText>
						<ns6:TypeCode>7130</ns6:TypeCode>
						<ns6:TypeCodelist>urn:fdc:ilismeta.interlis.ch:2017:NP_Typ_Kanton_Erschliessung_Linienobjekt.2407</ns6:TypeCodelist>
					</ns6:OtherLegend>
					<ns6:OtherLegend>
						<ns6:LegendText>
							<ns6:LocalisedText>
								<ns6:Language>de</ns6:Language>
								<ns6:Text>Baulinie Strasse</ns6:Text>
							</ns6:LocalisedText>
						</ns6:LegendText>
						<ns6:TypeCode>7200</ns6:TypeCode>
						<ns6:TypeCodelist>urn:fdc:ilismeta.interlis.ch:2017:NP_Typ_Kanton_Erschliessung_Linienobjekt.2407</ns6:TypeCodelist>
					</ns6:OtherLegend>

**Comment by claeis** [comment]
Das Problem ist m.E. dass es mehrere RestrictionOnLandownership mit dem selben Thema sind. Und wenn die alle den selben WMS haben, kann (muss?) der pdf4oereb das zu einer Seite zusammeführen, und dabei aber die OtherLegend Einträge weglassen, die einer  RestrictionOnLandownership  entsprechen, die zusammengeführt werden.

**Comment by edigonzales** [comment]
Ja. Leider verstehe ich es auch so, dass da noch was beim pdf4oereb gemacht werden muss.

**Comment by edigonzales** [comment]
https://github.com/openoereb/pdf4oereb/commit/83c9f03def623b0c7637fa71dadd7779125ce99c

Könnte hinkommen. Needs testing. Tricky war wiederum, dass man nicht nur den Aussagetext resp. den Artcode berücksichtigen darf, sondern die Typecodeliste mitschleppen muss.

[CH993287900649-other-legend.pdf](https://github.com/claeis/oereb-web-service/files/4560994/CH993287900649-other-legend.pdf)
[CH233274062061-other-legend.pdf](https://github.com/claeis/oereb-web-service/files/4560996/CH233274062061-other-legend.pdf)

**Comment by Luescher** [comment]
Passt nun. Merci. Das Ticket kann geschlossen werden
