### ISSUE TITLE
In /tmp häufen sich die Daten an

### ISSUE THREAD

**Issue by schmandr** [claeis/oereb-web-service#47]
In den Ordnern `/tmp/oerebwsnn` häufen sich im Lauf der Zeit immer mehr Daten an. Im Moment z.B. nach ca. 7 Wochen Laufzeit des Containers 3.6GB Daten. Mal 2, weil wir davon 2 Pods laufen haben.

Was lässt sich hier machen?

**Comment by edigonzales** [comment]
Die Anwendung sollte sich um das Aufräumen kümmern.

@claeis Soll ich mich daran wagen? Aus dem Kopf: Müsste aber sowas sein wie ein Cron-Putz-Job, der alle Daten im tmp löscht, die älter als XXX sind. Oder ginge das eleganter?
