### ISSUE TITLE
WMS GetMap case sensitive query parameters

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#49]
Das Auslesen der Query Parameter ist case senstive, z.B. https://github.com/claeis/oereb-web-service/blob/master/src/main/java/ch/ehi/oereb/webservice/OerebController.java#L2094 

So wie ich die WMS-Spez verstehe, müssen die Parameternamen nicht case sensitive sein.

Kontext: Das Bundestehma KbS-Flughafen verwendet kleingeschriebene Parameternamen. Z.B. CH340632730960 (Flughafen Grenchen) funktioniert nicht.

**Comment by claeis** [comment]
fixed in d9d04ed841f2dd90ed840debb8825c8f2d7400da
