### ISSUE TITLE
Bbox (min/max) of MapType

### ISSUE THREAD

**Issue by edigonzales** [claeis/oereb-web-service#63]
Sollten die Min-/Max-Elemente nicht immer erscheinen? https://github.com/claeis/oereb-web-service/blob/a8c86613595c9f5a5340610d85989b4a3fc22b24/src/main/java/ch/ehi/oereb/webservice/OerebController.java#L1528

Wird im Verifikationsbericht gemängelt und so wie ich das Schema lese, finde ich auch, dass sie immer vorhanden sein müssen.

**Comment by claeis** [comment]
ja, sehe ich auch so (zwei Stellen im Code)
